templates_predefined = read.csv("data-raw/templates_predefined.csv", stringsAsFactors = F)

templates_predefined_lookup = read.csv("data-raw/templates_predefined_lookup.csv", stringsAsFactors = F)

id_lookup = c(
  "aggregateOrganismObservationID"  = "aggregateOrganismObservationID",
  "attributeID"                     = "attributeID",                 
  "qualitativeAttributeID"          = "attributeID",
  "citationID"                      = "citationID",
  "accordingToCitationID"           = "citationID",
  "documentCitationID"              = "citationID",
  "interpretationCitationID"        = "citationID",
  "communityConceptID"              = "communityConceptID",
  "CommunityDetermination"          = "communityDeterminationID",
  "communityObservationID"          = "communityObservationID",
  "individualOrganismID"            = "individualOrganismID",
  "relatedIndividualID"             = "individualOrganismID",
  "individualOrganismObservationID" = "individualOrganismObservationID",
  "literatureCitationID"            = "literatureCitationID",
  "measurementID"                   = "measurementID",
  "methodID"                        = "methodID",
  "qualityAssessmentMethodID"       = "methodID",
  "observationGroupingID"           = "observationGroupingID",
  "organismIdentityID"              = "organismIdentityID",          
  "organismNameID"                  = "organismNameID",
  "originalOrganismNameID"          = "organismNameID",
  "partyID"                         = "partyID",
  "determinationPartyID"            = "partyID",
  "originalIdentificationPartyID"   = "partyID",
  "interpretationPartyID"           = "partyID",
  "conceptAssertionPartyID"         = "partyID",
  "placementPartyID"                = "partyID",
  "locationPartyID"                 = "partyID",
  "elevationPartyID"                = "partyID",
  "depthPartyID"                    = "partyID",
  "observationPartyID"              = "partyID",
  "plotID"                          = "plotID",
  "protocolID"                      = "protocolID",
  "relatedPlotID"                   = "plotID",
  "plotObservationID"               = "plotObservationID",
  "previousPlotObservationID"       = "plotObservationID",    
  "projectID"                       = "projectID",
  "relatedProjectID"                = "projectID",
  "protocolID"                      = "protocolID",
  "relatedItemID"                   = "relatedItemID",
  "siteObservationID"               = "siteObservationID",
  "stratumID"                       = "stratumID",
  "stratumObservationID"            = "stratumObservationID",
  "surfaceCoverObservationID"       = "surfaceCoverObservationID",
  "surfaceTypeID"                   = "surfaceTypeID",
  "taxonConceptID"                  = "taxonConceptID",
  "taxonDeterminationID"            = "taxonDeterminationID",
  "taxonDetermination"              = "taxonDeterminationID",
  "taxonNameID"                     = "taxonNameID",
  "preferredTaxonNameID"            = "taxonNameID",
  "taxonNameUsageConceptID"         = "taxonNameUsageConceptID",
  "vegXID"                          = "vegxID"
)

#### Export data ####
usethis::use_data(templates_predefined, templates_predefined_lookup, id_lookup, overwrite = TRUE, internal = TRUE)